# Generated by Django 2.0.4 on 2018-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvardit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sc_tx',
            field=models.CharField(default='0x', max_length=66),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sc_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
