# Generated by Django 2.0.4 on 2018-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvardit', '0002_auto_20180509_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sc_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
