# Generated by Django 2.0.4 on 2018-04-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyperledger_traceit', '0002_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='registrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hyperledger_traceit.Registrador'),
        ),
    ]
